// <auto-generated />
using System;
using AccountingSystem.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AccountingSystem.Infrastructure.Migrations
{
    [DbContext(typeof(AccountingDbContext))]
    [Migration("20260205083514_FixReportInstanceEnumColumns")]
    partial class FixReportInstanceEnumColumns
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "TaskStatus1", new[] { "Pending", "InProgress", "Done", "Paid", "NotRequired" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "audit_entity", new[] { "ReportInstance", "Task", "Company", "Worker" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "payment_method", new[] { "Credit", "Transfer", "Check", "Online", "Cash" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "report_status", new[] { "Pending", "Reported", "Paid", "Approved", "NotRequired" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "task_category", new[] { "Banks", "Income", "Expenses", "Reconciliations", "Other" });
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AccountingSystem.Domain.Entities.Accountingfirm", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("text")
                        .HasColumnName("address");

                    b.Property<DateTime?>("Createdat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("createdat")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<string>("Phone")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("phone");

                    b.Property<DateTime?>("Updatedat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updatedat")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id")
                        .HasName("accountingfirm_pkey");

                    b.ToTable("accountingfirm", (string)null);
                });

            modelBuilder.Entity("AccountingSystem.Domain.Entities.Auditlog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("action");

                    b.Property<DateTime?>("Createdat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("createdat")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("Entityid")
                        .HasColumnType("integer")
                        .HasColumnName("entityid");

                    b.Property<string>("Entitytype")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("entitytype");

                    b.Property<string>("Newvalue")
                        .HasColumnType("text")
                        .HasColumnName("newvalue");

                    b.Property<string>("Oldvalue")
                        .HasColumnType("text")
                        .HasColumnName("oldvalue");

                    b.Property<int>("Workerid")
                        .HasColumnType("integer")
                        .HasColumnName("workerid");

                    b.HasKey("Id")
                        .HasName("auditlog_pkey");

                    b.HasIndex(new[] { "Createdat" }, "idx_audit_created");

                    b.HasIndex(new[] { "Entitytype", "Entityid" }, "idx_audit_entity");

                    b.HasIndex(new[] { "Workerid" }, "idx_audit_worker");

                    b.ToTable("auditlog", (string)null);
                });

            modelBuilder.Entity("AccountingSystem.Domain.Entities.Company", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("text")
                        .HasColumnName("address");

                    b.Property<DateTime?>("Createdat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("createdat")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<int>("Firmid")
                        .HasColumnType("integer")
                        .HasColumnName("firmid");

                    b.Property<bool?>("Isactive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("isactive");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<string>("Phone")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("phone");

                    b.Property<string>("Taxid")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("taxid");

                    b.Property<DateTime?>("Updatedat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updatedat")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id")
                        .HasName("company_pkey");

                    b.HasIndex(new[] { "Taxid" }, "company_taxid_key")
                        .IsUnique();

                    b.HasIndex(new[] { "Firmid" }, "idx_company_firm");

                    b.HasIndex(new[] { "Taxid" }, "idx_company_taxid");

                    b.ToTable("company", (string)null);
                });

            modelBuilder.Entity("AccountingSystem.Domain.Entities.CompanyTask", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("Assignedworkerid")
                        .HasColumnType("integer")
                        .HasColumnName("assignedworkerid");

                    b.Property<int>("Companyid")
                        .HasColumnType("integer")
                        .HasColumnName("companyid");

                    b.Property<DateOnly?>("Completeddate")
                        .HasColumnType("date")
                        .HasColumnName("completeddate");

                    b.Property<DateTime?>("Createdat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("createdat")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateOnly?>("Duedate")
                        .HasColumnType("date")
                        .HasColumnName("duedate");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<DateOnly>("Period")
                        .HasColumnType("date")
                        .HasColumnName("period");

                    b.Property<int?>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("status")
                        .HasDefaultValueSql("'Pending'::\"TaskStatus1\"");

                    b.Property<int>("Tasktypeid")
                        .HasColumnType("integer")
                        .HasColumnName("tasktypeid");

                    b.Property<DateTime?>("Updatedat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updatedat")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id")
                        .HasName("task_pkey");

                    b.HasIndex("Tasktypeid");

                    b.HasIndex(new[] { "Assignedworkerid" }, "idx_task_assigned");

                    b.HasIndex(new[] { "Companyid", "Period" }, "idx_task_company_period");

                    b.HasIndex(new[] { "Companyid", "Tasktypeid", "Period" }, "uq_task_period")
                        .IsUnique();

                    b.ToTable("companytask", (string)null);
                });

            modelBuilder.Entity("AccountingSystem.Domain.Entities.Companycontact", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Companyid")
                        .HasColumnType("integer")
                        .HasColumnName("companyid");

                    b.Property<DateTime?>("Createdat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("createdat")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<string>("Firstname")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("firstname");

                    b.Property<bool?>("Isprimary")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("isprimary");

                    b.Property<string>("Lastname")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("lastname");

                    b.Property<string>("Phone")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("phone");

                    b.Property<string>("Position")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("position");

                    b.Property<DateTime?>("Updatedat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updatedat")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id")
                        .HasName("companycontact_pkey");

                    b.HasIndex(new[] { "Companyid" }, "idx_contact_company");

                    b.ToTable("companycontact", (string)null);
                });

            modelBuilder.Entity("AccountingSystem.Domain.Entities.Companyreportconfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Companyid")
                        .HasColumnType("integer")
                        .HasColumnName("companyid");

                    b.Property<DateTime?>("Createdat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("createdat")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<short?>("Dayofmonth")
                        .HasColumnType("smallint")
                        .HasColumnName("dayofmonth");

                    b.Property<int>("Frequencyid")
                        .HasColumnType("integer")
                        .HasColumnName("frequencyid");

                    b.Property<bool?>("Isactive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("isactive");

                    b.Property<int>("Reporttypeid")
                        .HasColumnType("integer")
                        .HasColumnName("reporttypeid");

                    b.Property<DateTime?>("Updatedat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updatedat")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("Year")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("year")
                        .HasDefaultValueSql("EXTRACT(year FROM CURRENT_DATE)");

                    b.HasKey("Id")
                        .HasName("companyreportconfig_pkey");

                    b.HasIndex("Frequencyid");

                    b.HasIndex("Reporttypeid");

                    b.HasIndex(new[] { "Companyid" }, "idx_config_company");

                    b.HasIndex(new[] { "Companyid", "Reporttypeid", "Year" }, "uq_company_report_year")
                        .IsUnique();

                    b.ToTable("companyreportconfig", (string)null);
                });

            modelBuilder.Entity("AccountingSystem.Domain.Entities.Companyworker", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("Assignedat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("assignedat")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("Companyid")
                        .HasColumnType("integer")
                        .HasColumnName("companyid");

                    b.Property<bool?>("Isactive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("isactive");

                    b.Property<int>("Workerid")
                        .HasColumnType("integer")
                        .HasColumnName("workerid");

                    b.HasKey("Id")
                        .HasName("companyworker_pkey");

                    b.HasIndex("Workerid");

                    b.HasIndex(new[] { "Companyid", "Workerid" }, "idx_company_worker");

                    b.HasIndex(new[] { "Companyid", "Workerid" }, "uq_company_worker")
                        .IsUnique();

                    b.ToTable("companyworker", (string)null);
                });

            modelBuilder.Entity("AccountingSystem.Domain.Entities.Frequency", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("Createdat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("createdat")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("frequency_pkey");

                    b.HasIndex(new[] { "Name" }, "frequency_name_key")
                        .IsUnique();

                    b.ToTable("frequency", (string)null);
                });

            modelBuilder.Entity("AccountingSystem.Domain.Entities.Reportinstance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("Amount")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("amount");

                    b.Property<string>("Comments")
                        .HasColumnType("text")
                        .HasColumnName("comments");

                    b.Property<int>("Configid")
                        .HasColumnType("integer")
                        .HasColumnName("configid");

                    b.Property<DateTime?>("Createdat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("createdat")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateOnly?>("Paiddate")
                        .HasColumnType("date")
                        .HasColumnName("paiddate");

                    b.Property<int?>("PaymentMethod")
                        .HasColumnType("payment_method")
                        .HasColumnName("paymentmethod");

                    b.Property<DateOnly>("Period")
                        .HasColumnType("date")
                        .HasColumnName("period");

                    b.Property<DateOnly?>("Receiptdate")
                        .HasColumnType("date")
                        .HasColumnName("receiptdate");

                    b.Property<DateOnly?>("Reporteddate")
                        .HasColumnType("date")
                        .HasColumnName("reporteddate");

                    b.Property<int?>("Status")
                        .HasColumnType("report_status")
                        .HasColumnName("status");

                    b.Property<DateTime?>("Updatedat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updatedat")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id")
                        .HasName("reportinstance_pkey");

                    b.HasIndex(new[] { "Configid" }, "idx_report_config");

                    b.HasIndex(new[] { "Period" }, "idx_report_period");

                    b.ToTable("reportinstance", (string)null);
                });

            modelBuilder.Entity("AccountingSystem.Domain.Entities.Reporttype", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("Createdat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("createdat")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<string>("Officialurl")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("officialurl");

                    b.Property<string>("Shortcode")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("shortcode");

                    b.HasKey("Id")
                        .HasName("reporttype_pkey");

                    b.ToTable("reporttype", (string)null);
                });

            modelBuilder.Entity("AccountingSystem.Domain.Entities.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("Createdat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("createdat")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("role_pkey");

                    b.HasIndex(new[] { "Name" }, "role_name_key")
                        .IsUnique();

                    b.ToTable("role", (string)null);
                });

            modelBuilder.Entity("AccountingSystem.Domain.Entities.Tasktype", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Category")
                        .HasColumnType("integer")
                        .HasColumnName("category");

                    b.Property<DateTime?>("Createdat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("createdat")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int?>("Defaultorder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(99)
                        .HasColumnName("defaultorder");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("tasktype_pkey");

                    b.ToTable("tasktype", (string)null);
                });

            modelBuilder.Entity("AccountingSystem.Domain.Entities.VwActivetasks", b =>
                {
                    b.Property<string>("Assignedworkername")
                        .HasColumnType("text")
                        .HasColumnName("assignedworkername");

                    b.Property<int?>("Category")
                        .HasColumnType("integer")
                        .HasColumnName("category");

                    b.Property<string>("Companyname")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("companyname");

                    b.Property<DateTime?>("Createdat")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("createdat");

                    b.Property<DateOnly?>("Duedate")
                        .HasColumnType("date")
                        .HasColumnName("duedate");

                    b.Property<int?>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<DateOnly?>("Period")
                        .HasColumnType("date")
                        .HasColumnName("period");

                    b.Property<int?>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<string>("Tasktypename")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("tasktypename");

                    b.Property<DateTime?>("Updatedat")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updatedat");

                    b.ToTable((string)null);

                    b.ToView("vw_activetasks", (string)null);
                });

            modelBuilder.Entity("AccountingSystem.Domain.Entities.VwCompanydetails", b =>
                {
                    b.Property<string>("Companyname")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("companyname");

                    b.Property<DateTime?>("Createdat")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("createdat");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<string>("Firmemail")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("firmemail");

                    b.Property<string>("Firmname")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("firmname");

                    b.Property<int?>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<bool?>("Isactive")
                        .HasColumnType("boolean")
                        .HasColumnName("isactive");

                    b.Property<string>("Phone")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("phone");

                    b.Property<string>("Taxid")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("taxid");

                    b.Property<DateTime?>("Updatedat")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updatedat");

                    b.ToTable((string)null);

                    b.ToView("vw_companydetails", (string)null);
                });

            modelBuilder.Entity("AccountingSystem.Domain.Entities.VwUpcomingreports", b =>
                {
                    b.Property<decimal?>("Amount")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("amount");

                    b.Property<string>("Companyname")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("companyname");

                    b.Property<short?>("Dayofmonth")
                        .HasColumnType("smallint")
                        .HasColumnName("dayofmonth");

                    b.Property<int?>("Daysoverdue")
                        .HasColumnType("integer")
                        .HasColumnName("daysoverdue");

                    b.Property<int?>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<DateOnly?>("Period")
                        .HasColumnType("date")
                        .HasColumnName("period");

                    b.Property<string>("Reporttypename")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("reporttypename");

                    b.Property<string>("Shortcode")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("shortcode");

                    b.Property<int?>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.ToTable((string)null);

                    b.ToView("vw_upcomingreports", (string)null);
                });

            modelBuilder.Entity("AccountingSystem.Domain.Entities.VwWorkercompanies", b =>
                {
                    b.Property<DateTime?>("Assignedat")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("assignedat");

                    b.Property<int?>("Companyid")
                        .HasColumnType("integer")
                        .HasColumnName("companyid");

                    b.Property<string>("Companyname")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("companyname");

                    b.Property<bool?>("Isactive")
                        .HasColumnType("boolean")
                        .HasColumnName("isactive");

                    b.Property<string>("Workeremail")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("workeremail");

                    b.Property<int?>("Workerid")
                        .HasColumnType("integer")
                        .HasColumnName("workerid");

                    b.Property<string>("Workername")
                        .HasColumnType("text")
                        .HasColumnName("workername");

                    b.ToTable((string)null);

                    b.ToView("vw_workercompanies", (string)null);
                });

            modelBuilder.Entity("AccountingSystem.Domain.Entities.Worker", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AuthProvider")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("authprovider")
                        .HasDefaultValueSql("'Local'::character varying");

                    b.Property<DateTime?>("Createdat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("createdat")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<string>("Employeeid")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("employeeid");

                    b.Property<int>("Firmid")
                        .HasColumnType("integer")
                        .HasColumnName("firmid");

                    b.Property<string>("Firstname")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("firstname");

                    b.Property<string>("GoogleId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("googleid");

                    b.Property<DateOnly?>("Hiredate")
                        .HasColumnType("date")
                        .HasColumnName("hiredate");

                    b.Property<bool?>("Isactive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("isactive");

                    b.Property<string>("Lastname")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("lastname");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("passwordhash")
                        .HasDefaultValueSql("''::character varying");

                    b.Property<string>("Phone")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("phone");

                    b.Property<int>("Roleid")
                        .HasColumnType("integer")
                        .HasColumnName("roleid");

                    b.Property<DateTime?>("Updatedat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updatedat")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id")
                        .HasName("worker_pkey");

                    b.HasIndex("Roleid");

                    b.HasIndex(new[] { "Email" }, "idx_worker_email");

                    b.HasIndex(new[] { "Firmid" }, "idx_worker_firm");

                    b.HasIndex(new[] { "Email" }, "worker_email_key")
                        .IsUnique();

                    b.ToTable("worker", (string)null);
                });

            modelBuilder.Entity("AccountingSystem.Domain.Entities.Workerroletype", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("workerroletype_pkey");

                    b.HasIndex(new[] { "Name" }, "workerroletype_name_key")
                        .IsUnique();

                    b.ToTable("workerroletype", (string)null);
                });

            modelBuilder.Entity("AccountingSystem.Domain.Entities.Auditlog", b =>
                {
                    b.HasOne("AccountingSystem.Domain.Entities.Worker", "Worker")
                        .WithMany("Auditlogs")
                        .HasForeignKey("Workerid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_audit_worker");

                    b.Navigation("Worker");
                });

            modelBuilder.Entity("AccountingSystem.Domain.Entities.Company", b =>
                {
                    b.HasOne("AccountingSystem.Domain.Entities.Accountingfirm", "Firm")
                        .WithMany("Companies")
                        .HasForeignKey("Firmid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_company_firm");

                    b.Navigation("Firm");
                });

            modelBuilder.Entity("AccountingSystem.Domain.Entities.CompanyTask", b =>
                {
                    b.HasOne("AccountingSystem.Domain.Entities.Worker", "Assignedworker")
                        .WithMany("CompanyTasks")
                        .HasForeignKey("Assignedworkerid")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_task_worker");

                    b.HasOne("AccountingSystem.Domain.Entities.Company", "Company")
                        .WithMany("CompanyTasks")
                        .HasForeignKey("Companyid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_task_company");

                    b.HasOne("AccountingSystem.Domain.Entities.Tasktype", "Tasktype")
                        .WithMany("CompanyTasks")
                        .HasForeignKey("Tasktypeid")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_task_tasktype");

                    b.Navigation("Assignedworker");

                    b.Navigation("Company");

                    b.Navigation("Tasktype");
                });

            modelBuilder.Entity("AccountingSystem.Domain.Entities.Companycontact", b =>
                {
                    b.HasOne("AccountingSystem.Domain.Entities.Company", "Company")
                        .WithMany("Companycontacts")
                        .HasForeignKey("Companyid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_contact_company");

                    b.Navigation("Company");
                });

            modelBuilder.Entity("AccountingSystem.Domain.Entities.Companyreportconfig", b =>
                {
                    b.HasOne("AccountingSystem.Domain.Entities.Company", "Company")
                        .WithMany("Companyreportconfigs")
                        .HasForeignKey("Companyid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_config_company");

                    b.HasOne("AccountingSystem.Domain.Entities.Frequency", "Frequency")
                        .WithMany("Companyreportconfigs")
                        .HasForeignKey("Frequencyid")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_config_frequency");

                    b.HasOne("AccountingSystem.Domain.Entities.Reporttype", "Reporttype")
                        .WithMany("Companyreportconfigs")
                        .HasForeignKey("Reporttypeid")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_config_reporttype");

                    b.Navigation("Company");

                    b.Navigation("Frequency");

                    b.Navigation("Reporttype");
                });

            modelBuilder.Entity("AccountingSystem.Domain.Entities.Companyworker", b =>
                {
                    b.HasOne("AccountingSystem.Domain.Entities.Company", "Company")
                        .WithMany("Companyworkers")
                        .HasForeignKey("Companyid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_companyworker_company");

                    b.HasOne("AccountingSystem.Domain.Entities.Worker", "Worker")
                        .WithMany("Companyworkers")
                        .HasForeignKey("Workerid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_companyworker_worker");

                    b.Navigation("Company");

                    b.Navigation("Worker");
                });

            modelBuilder.Entity("AccountingSystem.Domain.Entities.Reportinstance", b =>
                {
                    b.HasOne("AccountingSystem.Domain.Entities.Companyreportconfig", "Config")
                        .WithMany("Reportinstances")
                        .HasForeignKey("Configid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_instance_config");

                    b.Navigation("Config");
                });

            modelBuilder.Entity("AccountingSystem.Domain.Entities.Worker", b =>
                {
                    b.HasOne("AccountingSystem.Domain.Entities.Accountingfirm", "Firm")
                        .WithMany("Workers")
                        .HasForeignKey("Firmid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_worker_firm");

                    b.HasOne("AccountingSystem.Domain.Entities.Role", "Role")
                        .WithMany("Workers")
                        .HasForeignKey("Roleid")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_worker_role");

                    b.Navigation("Firm");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("AccountingSystem.Domain.Entities.Accountingfirm", b =>
                {
                    b.Navigation("Companies");

                    b.Navigation("Workers");
                });

            modelBuilder.Entity("AccountingSystem.Domain.Entities.Company", b =>
                {
                    b.Navigation("CompanyTasks");

                    b.Navigation("Companycontacts");

                    b.Navigation("Companyreportconfigs");

                    b.Navigation("Companyworkers");
                });

            modelBuilder.Entity("AccountingSystem.Domain.Entities.Companyreportconfig", b =>
                {
                    b.Navigation("Reportinstances");
                });

            modelBuilder.Entity("AccountingSystem.Domain.Entities.Frequency", b =>
                {
                    b.Navigation("Companyreportconfigs");
                });

            modelBuilder.Entity("AccountingSystem.Domain.Entities.Reporttype", b =>
                {
                    b.Navigation("Companyreportconfigs");
                });

            modelBuilder.Entity("AccountingSystem.Domain.Entities.Role", b =>
                {
                    b.Navigation("Workers");
                });

            modelBuilder.Entity("AccountingSystem.Domain.Entities.Tasktype", b =>
                {
                    b.Navigation("CompanyTasks");
                });

            modelBuilder.Entity("AccountingSystem.Domain.Entities.Worker", b =>
                {
                    b.Navigation("Auditlogs");

                    b.Navigation("CompanyTasks");

                    b.Navigation("Companyworkers");
                });
#pragma warning restore 612, 618
        }
    }
}
